# 触发「重大事件快讯」的关键词/正则。区分大小写与否由 ignore_case 控制。
ignore_case: true
groups:
  - name: 新模型/版本
    patterns:
      - "发布.*(模型|大模型|Model)"
      - "GPT|Claude|Gemini|Qwen|GLM|Llama|Mixtral"
  - name: 开源/SOTA
    patterns:
      - "开源|open\s*source"
      - "SOTA|state[-\s]*of[-\s]*the[-\s]*art"
  - name: 价格/商业策略
    patterns:
      - "降价|涨价|价格|pricing"
      - "订阅|pro|plus|enterprise"
  - name: 生态破圈
    patterns:
      - "爆火|刷屏|破圈|trending"
