name: Daily Digest

on:
  schedule:
    - cron: "0 0 * * *"  # 00:00 UTC daily
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Generate report
        env:
          TIMEZONE: Asia/Shanghai
          REPORT_TIME_WINDOW_HOURS: '24'
          HTTP_TIMEOUT: '20'
          USER_AGENT: ai-intelligence-hub/1.0 (GitHub Actions)
        run: |
          python scripts/generate_report.py

      - name: Commit and push if changed
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            today=$(date -u +"%Y-%m-%d")
            git add -A
            git commit -m "chore: daily report ${today}"
            git push
          else
            echo "No changes to commit."
          fi

