name: Daily AI Digest

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]        # 首次验证非常有用：随便改个 README 触发一次
  schedule:
    - cron: '0 1,13 * * *'    # UTC 01:00/13:00 → CST 09:00/21:00

permissions:
  contents: write             # 允许后续自动 commit & push

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Sanity check
        run: echo "✅ GitHub Actions is running."

  build:
    needs: sanity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Generate daily report (+quick alerts)
        run: |
          python scripts/generate_report.py

      - name: Commit & Push
        run: |
          git config user.name "ai-bot"
          git config user.email "ai-bot@users.noreply.github.com"
          git add -A
          git diff --quiet && echo "No changes" || git commit -m "chore(report): auto daily report + alerts"
          git push
