name: Daily AI Digest

on:
  schedule:
    # UTC 时间：01:00 与 13:00（对应 CST 09:00 / 21:00）
    - cron: '0 1,13 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
      - name: Generate daily report (+quick alerts)
        run: |
          python scripts/generate_report.py
      - name: Commit & Push
        run: |
          git config user.name "ai-bot"
          git config user.email "ai-bot@users.noreply.github.com"
          git add -A
          git diff --quiet && echo "No changes" || git commit -m "chore(report): auto daily report + alerts"
          git push
